/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 town.gltf --transform
Author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fishing-town-907592e0212c41e9b23cf792dd962d88
Title: Fishing Town
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/town-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_1.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_4_1.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_85.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_86.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_87.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_154.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_171.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_173.geometry}
        material={materials.lpb_gradient}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.lpb_gradient}
        position={[1.946, 1.53, 3.993]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.lpb_gradient_metal}
        position={[1.946, 3.966, 4.335]}
        scale={0.536}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.material}
        position={[0.29, -0.029, 0.356]}
        scale={12.986}
      />
    </group>
  );
}

useGLTF.preload("/town-transformed.glb");
